### ISSUE TITLE
Issue when asking to resend confirmation mail

### ISSUE THREAD

**Issue by Sturgelose** [educloudalliance/educloud-knowhow#21]
When asking for a new confirmation mail (resend), the server throws an error. Mail is never received.

https://knowhow.educloudalliance.org/confirm

```
Question2Answer fatal error:
Could not send email confirmation

Stack trace:

require() in index.php:31
require() in qa-index.php:175
qa_get_request_content() in qa-page.php:789
require() in qa-page.php:207
qa_send_new_confirm() in qa-page-confirm.php:54
```

![image](https://cloud.githubusercontent.com/assets/244191/6127012/fd25506c-b12e-11e4-92de-08eeffa992eb.png)

**Comment by kyyberi** [comment]
Fixed
